/**
 * PDF Generation Service for MYDSCVR Core Features
 *
 * Generates professional PDF reports for:
 * - Document validation reports
 * - Travel itineraries
 * - Photo compliance reports
 */

import PDFDocument from 'pdfkit';
import { uploadBuffer } from './storage.js';

// ============================================
// DOCUMENT VALIDATION REPORT PDF
// ============================================

interface ValidationReportData {
  documentType: string;
  score: number;
  issues: {
    severity: 'critical' | 'warning' | 'info';
    category: string;
    description: string;
    location?: string;
  }[];
  validationReport: {
    attestationCheck: { passed: boolean; details: string };
    signatureCheck: { passed: boolean; details: string };
    formatCheck: { passed: boolean; details: string };
    expiryCheck: { passed: boolean; details: string };
    legibilityCheck: { passed: boolean; details: string };
  };
  createdAt: Date;
}

export async function generateValidationReportPDF(
  validationId: number,
  userId: string,
  data: ValidationReportData
): Promise<string> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', async () => {
      try {
        const pdfBuffer = Buffer.concat(chunks);
        const key = `reports/${userId}/validation-${validationId}.pdf`;
        const url = await uploadBuffer(pdfBuffer, key, 'application/pdf');
        resolve(url);
      } catch (error) {
        reject(error);
      }
    });

    // Header
    doc.fontSize(24).fillColor('#1e40af').text('Document Validation Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(12).fillColor('#6b7280').text(`Generated: ${new Date().toLocaleDateString()}`, { align: 'center' });
    doc.moveDown(2);

    // Document Type
    doc.fontSize(14).fillColor('#374151').text(`Document Type: ${data.documentType.replace(/_/g, ' ').toUpperCase()}`);
    doc.moveDown();

    // Overall Score
    const scoreColor = data.score >= 80 ? '#10b981' : data.score >= 60 ? '#f59e0b' : '#ef4444';
    doc.fontSize(18).fillColor(scoreColor).text(`Compliance Score: ${data.score}/100`, { align: 'center' });
    doc.moveDown(2);

    // Validation Checks
    doc.fontSize(16).fillColor('#1f2937').text('Validation Checks');
    doc.moveDown();

    const checks = [
      { name: 'Attestation Check', ...data.validationReport.attestationCheck },
      { name: 'Signature Check', ...data.validationReport.signatureCheck },
      { name: 'Format Check', ...data.validationReport.formatCheck },
      { name: 'Expiry Check', ...data.validationReport.expiryCheck },
      { name: 'Legibility Check', ...data.validationReport.legibilityCheck },
    ];

    checks.forEach((check) => {
      const icon = check.passed ? '✓' : '✗';
      const color = check.passed ? '#10b981' : '#ef4444';
      doc.fontSize(12).fillColor(color).text(`${icon} ${check.name}`, { continued: true });
      doc.fillColor('#6b7280').text(` - ${check.details}`);
      doc.moveDown(0.5);
    });

    doc.moveDown();

    // Issues Found
    if (data.issues.length > 0) {
      doc.fontSize(16).fillColor('#1f2937').text('Issues Found');
      doc.moveDown();

      data.issues.forEach((issue) => {
        const severityColors = {
          critical: '#ef4444',
          warning: '#f59e0b',
          info: '#3b82f6',
        };
        doc.fontSize(12).fillColor(severityColors[issue.severity]).text(`[${issue.severity.toUpperCase()}] ${issue.category}`);
        doc.fontSize(10).fillColor('#374151').text(issue.description);
        if (issue.location) {
          doc.fontSize(10).fillColor('#6b7280').text(`Recommendation: ${issue.location}`);
        }
        doc.moveDown();
      });
    } else {
      doc.fontSize(14).fillColor('#10b981').text('No issues found. Document appears to be compliant.');
    }

    doc.moveDown(2);

    // Footer
    doc.fontSize(10).fillColor('#9ca3af').text('This report was generated by MYDSCVR AI Document Validator.', { align: 'center' });
    doc.text('For official legal advice, please consult a licensed immigration consultant.', { align: 'center' });

    doc.end();
  });
}

// ============================================
// TRAVEL ITINERARY PDF
// ============================================

interface ItineraryPDFData {
  destination: string;
  countries: string[];
  duration: number;
  startDate: string;
  endDate: string;
  travelPurpose: string;
  budget: string;
  itinerary: {
    day: number;
    date: string;
    city: string;
    country: string;
    activities: {
      time: string;
      activity: string;
      location: string;
      description: string;
    }[];
    accommodation: {
      name: string;
      address: string;
      checkIn: string;
      checkOut: string;
      confirmationNumber: string;
    };
    transportation: {
      type: string;
      from: string;
      to: string;
      time: string;
      details: string;
    }[];
  }[];
  flightDetails: {
    outbound: {
      airline: string;
      flightNumber: string;
      departure: { airport: string; time: string; date: string };
      arrival: { airport: string; time: string; date: string };
    };
    return: {
      airline: string;
      flightNumber: string;
      departure: { airport: string; time: string; date: string };
      arrival: { airport: string; time: string; date: string };
    };
  };
}

export async function generateTravelItineraryPDF(
  itineraryId: number,
  userId: string,
  data: ItineraryPDFData
): Promise<string> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', async () => {
      try {
        const pdfBuffer = Buffer.concat(chunks);
        const key = `reports/${userId}/itinerary-${itineraryId}.pdf`;
        const url = await uploadBuffer(pdfBuffer, key, 'application/pdf');
        resolve(url);
      } catch (error) {
        reject(error);
      }
    });

    // Header
    doc.fontSize(24).fillColor('#d97706').text('Travel Itinerary', { align: 'center' });
    doc.moveDown();
    doc.fontSize(16).fillColor('#374151').text(data.destination, { align: 'center' });
    doc.moveDown(2);

    // Trip Overview
    doc.fontSize(14).fillColor('#1f2937').text('Trip Overview');
    doc.moveDown(0.5);
    doc.fontSize(11).fillColor('#374151');
    doc.text(`Duration: ${data.duration} days`);
    doc.text(`Dates: ${data.startDate} to ${data.endDate}`);
    doc.text(`Purpose: ${data.travelPurpose}`);
    if (data.countries.length > 0) {
      doc.text(`Countries: ${data.countries.join(', ')}`);
    }
    doc.moveDown(2);

    // Flight Information
    doc.fontSize(14).fillColor('#1f2937').text('Flight Information');
    doc.moveDown(0.5);

    // Outbound Flight
    doc.fontSize(12).fillColor('#2563eb').text('Outbound Flight');
    doc.fontSize(10).fillColor('#374151');
    doc.text(`${data.flightDetails.outbound.airline} ${data.flightDetails.outbound.flightNumber}`);
    doc.text(`Departure: ${data.flightDetails.outbound.departure.airport} at ${data.flightDetails.outbound.departure.time} on ${data.flightDetails.outbound.departure.date}`);
    doc.text(`Arrival: ${data.flightDetails.outbound.arrival.airport} at ${data.flightDetails.outbound.arrival.time} on ${data.flightDetails.outbound.arrival.date}`);
    doc.moveDown();

    // Return Flight
    doc.fontSize(12).fillColor('#2563eb').text('Return Flight');
    doc.fontSize(10).fillColor('#374151');
    doc.text(`${data.flightDetails.return.airline} ${data.flightDetails.return.flightNumber}`);
    doc.text(`Departure: ${data.flightDetails.return.departure.airport} at ${data.flightDetails.return.departure.time} on ${data.flightDetails.return.departure.date}`);
    doc.text(`Arrival: ${data.flightDetails.return.arrival.airport} at ${data.flightDetails.return.arrival.time} on ${data.flightDetails.return.arrival.date}`);
    doc.moveDown(2);

    // Daily Itinerary
    doc.fontSize(14).fillColor('#1f2937').text('Daily Itinerary');
    doc.moveDown();

    data.itinerary.forEach((day) => {
      // Check if we need a new page
      if (doc.y > 650) {
        doc.addPage();
      }

      doc.fontSize(13).fillColor('#d97706').text(`Day ${day.day} - ${day.date}`);
      doc.fontSize(11).fillColor('#6b7280').text(`${day.city}, ${day.country}`);
      doc.moveDown(0.5);

      // Activities
      day.activities.forEach((activity) => {
        doc.fontSize(10).fillColor('#374151');
        doc.text(`${activity.time} - ${activity.activity}`, { continued: false });
        doc.fontSize(9).fillColor('#6b7280').text(`  📍 ${activity.location}`);
        doc.text(`  ${activity.description}`);
        doc.moveDown(0.3);
      });

      // Accommodation
      doc.moveDown(0.5);
      doc.fontSize(11).fillColor('#059669').text('🏨 Accommodation');
      doc.fontSize(10).fillColor('#374151');
      doc.text(`${day.accommodation.name}`);
      doc.fontSize(9).fillColor('#6b7280');
      doc.text(`Address: ${day.accommodation.address}`);
      doc.text(`Check-in: ${day.accommodation.checkIn} | Check-out: ${day.accommodation.checkOut}`);
      doc.text(`Confirmation: ${day.accommodation.confirmationNumber}`);
      doc.moveDown();

      // Transportation (if any)
      if (day.transportation.length > 0) {
        doc.fontSize(11).fillColor('#7c3aed').text('🚌 Transportation');
        day.transportation.forEach((transport) => {
          doc.fontSize(9).fillColor('#374151');
          doc.text(`${transport.time} - ${transport.type}: ${transport.from} → ${transport.to}`);
          doc.fillColor('#6b7280').text(`  ${transport.details}`);
        });
        doc.moveDown();
      }

      doc.moveDown();
    });

    // Footer
    doc.fontSize(10).fillColor('#9ca3af').text('This itinerary was generated by MYDSCVR AI Travel Itinerary Generator.', { align: 'center' });
    doc.text('All hotel and flight information is for visa application purposes.', { align: 'center' });

    doc.end();
  });
}

// ============================================
// PHOTO COMPLIANCE REPORT PDF
// ============================================

interface PhotoComplianceReportData {
  visaType: string;
  results: {
    photoUrl: string;
    compliant: boolean;
    issues: {
      dimension: boolean;
      background: boolean;
      faceSize: boolean;
      lighting: boolean;
      quality: boolean;
    };
    score: number;
  }[];
  specifications: {
    requiredDimensions: string;
    requiredBackground: string;
    requiredFaceSize: string;
  };
}

export async function generatePhotoComplianceReportPDF(
  complianceId: number,
  userId: string,
  data: PhotoComplianceReportData
): Promise<string> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', async () => {
      try {
        const pdfBuffer = Buffer.concat(chunks);
        const key = `reports/${userId}/photo-compliance-${complianceId}.pdf`;
        const url = await uploadBuffer(pdfBuffer, key, 'application/pdf');
        resolve(url);
      } catch (error) {
        reject(error);
      }
    });

    // Header
    doc.fontSize(24).fillColor('#7c3aed').text('Photo Compliance Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(14).fillColor('#374151').text(data.visaType.replace(/_/g, ' ').toUpperCase(), { align: 'center' });
    doc.moveDown(2);

    // Specifications
    doc.fontSize(14).fillColor('#1f2937').text('Required Specifications');
    doc.moveDown(0.5);
    doc.fontSize(11).fillColor('#374151');
    doc.text(`Dimensions: ${data.specifications.requiredDimensions}`);
    doc.text(`Background: ${data.specifications.requiredBackground}`);
    doc.text(`Face Size: ${data.specifications.requiredFaceSize}`);
    doc.moveDown(2);

    // Results
    doc.fontSize(14).fillColor('#1f2937').text('Photo Analysis Results');
    doc.moveDown();

    data.results.forEach((result, index) => {
      const overallStatus = result.compliant ? '✓ COMPLIANT' : '✗ NON-COMPLIANT';
      const statusColor = result.compliant ? '#10b981' : '#ef4444';

      doc.fontSize(12).fillColor(statusColor).text(`Photo ${index + 1}: ${overallStatus}`);
      doc.fontSize(11).fillColor('#374151').text(`Score: ${result.score}/100`);
      doc.moveDown(0.5);

      // Individual checks
      const checks = [
        { name: 'Dimensions', passed: result.issues.dimension },
        { name: 'Background', passed: result.issues.background },
        { name: 'Face Size', passed: result.issues.faceSize },
        { name: 'Lighting', passed: result.issues.lighting },
        { name: 'Quality', passed: result.issues.quality },
      ];

      checks.forEach((check) => {
        const icon = check.passed ? '✓' : '✗';
        const color = check.passed ? '#10b981' : '#ef4444';
        doc.fontSize(10).fillColor(color).text(`  ${icon} ${check.name}`);
      });

      doc.moveDown();
    });

    // Footer
    doc.moveDown(2);
    doc.fontSize(10).fillColor('#9ca3af').text('This report was generated by MYDSCVR AI Photo Compliance Checker.', { align: 'center' });
    doc.text('Ensure your photos meet all requirements before submission.', { align: 'center' });

    doc.end();
  });
}
